"""
llm_agent.py
THE AI-POWERED LAYER of the project — running on Google's Gemini API
(free tier: Gemini 2.5 Flash, no credit card required).

Everything else in this codebase (header parsing, URL/typosquat checks, QR
decoding, attachment scanning, PDF structural checks) is deterministic
security engineering that gathers *evidence*. This module is where an LLM
actually reasons over that evidence to produce a verdict, a confidence
score, and a human-readable explanation -- specifically judging things like
tone, urgency, social engineering intent, and (for screenshots/PDFs) visual
mimicry, which genuinely can't be done with regex/rules alone.

Requires GEMINI_API_KEY to be set in the environment (see .env.example).
Get a free key at https://aistudio.google.com
"""

import os
import json
import google.generativeai as genai

MODEL = "gemini-2.5-flash"

SYSTEM_PROMPT = """You are a cybersecurity analyst assistant specializing in phishing triage.

You will be given content (an email, a screenshot, or a PDF) along with
pre-computed security signals produced by deterministic tools (SPF/DKIM/DMARC
results, URL analysis, typosquat detection, brand impersonation checks, QR
code findings, attachment risk flags, or PDF structural flags). Treat this
evidence as trustworthy -- it was not generated by you.

Your job is to reason over ALL of this evidence together and produce a final
verdict. Specifically:
1. Identify social engineering techniques used in the text (urgency,
   authority impersonation, fear, curiosity/reward bait, generic greetings,
   requests for credentials or payment, etc.)
2. Weigh the technical evidence (auth failures, typosquats, suspicious URLs,
   risky attachments, QR codes, PDF structural risks) alongside textual and
   (if provided) visual cues.
3. Produce a verdict: "phishing", "suspicious", or "legitimate".
4. Produce a confidence score from 5-95. NEVER use 0 or 100 -- some
   uncertainty always remains, even in clear-cut cases. Only go above 90 if
   there are two or more independent strong signals reinforcing each other
   (e.g. failed auth AND a typosquat domain AND urgent credential-request
   language together). A single signal alone should generally stay in the
   40-70 range, not higher.
5. Explain your reasoning in 3-6 concise bullet points a non-technical reader
   could understand.

Respond ONLY with valid JSON in this exact shape, nothing else, no markdown fences:
{
  "verdict": "phishing" | "suspicious" | "legitimate",
  "confidence": <integer 5-95>,
  "techniques_detected": ["..."],
  "reasoning": ["...", "...", "..."]
}
"""


def _clamp_confidence(verdict: dict) -> dict:
    """
    Safety net in case the model ignores the 5-95 instruction in the prompt.
    Guarantees the final output never claims absolute (0 or 100) certainty,
    regardless of what Gemini actually returns.
    """
    if isinstance(verdict, dict) and "confidence" in verdict:
        try:
            verdict["confidence"] = max(5, min(95, int(verdict["confidence"])))
        except (TypeError, ValueError):
            pass
    return verdict


def _parse_json_response(raw_text: str) -> dict:
    """Shared cleanup + parsing for all three verdict paths."""
    raw_text = raw_text.strip().strip("`")
    if raw_text.lower().startswith("json"):
        raw_text = raw_text[4:].strip()

    try:
        return json.loads(raw_text)
    except json.JSONDecodeError as e:
        return {
            "verdict": "unknown",
            "confidence": 0,
            "techniques_detected": [],
            "reasoning": [f"Response could not be parsed as JSON: {e}", f"Raw response: {raw_text[:300]}"],
        }


# ---------------------------------------------------------------------------
# 1. Standard .eml / raw email text path
# ---------------------------------------------------------------------------

def _build_email_prompt(email_summary: dict) -> str:
    return f"""EMAIL CONTENT
Subject: {email_summary['subject']}
From: {email_summary['sender']} (domain: {email_summary['sender_domain']})
Reply-To: {email_summary.get('reply_to', 'N/A')}

Body:
{email_summary['body_text'][:4000]}

---
PRE-COMPUTED SECURITY EVIDENCE (from deterministic tools)

Auth headers (SPF/DKIM/DMARC): {json.dumps(email_summary.get('auth_summary', {}))}
Auth risk flags: {email_summary.get('auth_flags', [])}

URL analysis: {json.dumps(email_summary.get('url_analysis', []), indent=None)}

Brand impersonation check: {json.dumps(email_summary.get('brand_check', {}))}

QR code findings: {json.dumps(email_summary.get('qr_findings', []))}

Attachment risk scan: {json.dumps(email_summary.get('attachment_scan', []))}

---
Based on ALL of the above, produce your verdict as JSON per the system instructions."""


def get_verdict(email_summary: dict, api_key: str = None) -> dict:
    """
    email_summary: a dict combining parsed email fields + all deterministic
    module outputs (see main.py for how this is assembled).

    Returns the parsed JSON verdict dict, confidence-clamped to 5-95.
    """
    genai.configure(api_key=api_key or os.environ.get("GEMINI_API_KEY"))

    model = genai.GenerativeModel(
        model_name=MODEL,
        system_instruction=SYSTEM_PROMPT,
        generation_config={"response_mime_type": "application/json"},
    )

    try:
        response = model.generate_content(_build_email_prompt(email_summary))
        raw_text = "".join(
            part.text for part in response.candidates[0].content.parts if hasattr(part, "text")
        ) if hasattr(response, "candidates") else response.text
    except Exception as e:
        return {
            "verdict": "unknown",
            "confidence": 0,
            "techniques_detected": [],
            "reasoning": [f"Gemini API call failed: {e}"],
        }

    return _clamp_confidence(_parse_json_response(raw_text))


# ---------------------------------------------------------------------------
# 2. Screenshot path
# ---------------------------------------------------------------------------

def get_verdict_from_screenshot(image_bytes: bytes, ocr_text: str, url_analysis: list, api_key: str = None) -> dict:
    """
    Screenshot-specific verdict path. Sends Gemini BOTH the raw image (so it
    can visually judge fake login pages, spoofed logos, layout mimicry) AND
    the OCR-extracted text + deterministic URL analysis as supporting evidence.

    Note: no SPF/DKIM/sender-domain data is available from a screenshot alone,
    so this path is inherently weaker evidence than a raw .eml -- worth
    mentioning as a known limitation.
    """
    genai.configure(api_key=api_key or os.environ.get("GEMINI_API_KEY"))

    model = genai.GenerativeModel(
        model_name=MODEL,
        system_instruction=SYSTEM_PROMPT + "\n\nNote: this input is a SCREENSHOT, not raw email "
        "source. No SPF/DKIM/sender-domain data is available. Judge visual cues (fake login "
        "pages, spoofed branding/logos, mismatched URLs shown on screen) in addition to text.",
        generation_config={"response_mime_type": "application/json"},
    )

    prompt = f"""SCREENSHOT ANALYSIS

OCR-extracted text from the screenshot:
{ocr_text[:3000]}

URLs found in that text (with typosquat/shortener analysis):
{json.dumps(url_analysis, indent=None)}

Analyze the attached image directly for phishing indicators (fake login forms,
brand impersonation, suspicious visual layout) combined with the text evidence
above. Respond with the same JSON verdict shape as usual."""

    try:
        response = model.generate_content([
            {"mime_type": "image/png", "data": image_bytes},
            prompt,
        ])
        raw_text = response.text
    except Exception as e:
        return {
            "verdict": "unknown",
            "confidence": 0,
            "techniques_detected": [],
            "reasoning": [f"Screenshot analysis failed: {e}"],
        }

    return _clamp_confidence(_parse_json_response(raw_text))


# ---------------------------------------------------------------------------
# 3. PDF path
# ---------------------------------------------------------------------------

def get_verdict_from_pdf(page_image_bytes: bytes, extracted_text: str, link_annotations: list,
                          url_analysis: list, risk_flags: dict, api_key: str = None) -> dict:
    """
    PDF-specific verdict path. Sends Gemini the rendered first page (visual
    judgment: fake letterhead, spoofed branding, mimicked e-signature UI)
    plus extracted text, link annotations (which can differ from visible
    text -- a classic PDF phishing trick), and structural risk flags
    (embedded JS, embedded files, encryption).
    """
    genai.configure(api_key=api_key or os.environ.get("GEMINI_API_KEY"))

    model = genai.GenerativeModel(
        model_name=MODEL,
        system_instruction=SYSTEM_PROMPT + "\n\nNote: this input is a PDF document. Pay special "
        "attention to any mismatch between what link annotations claim to point to and their "
        "actual URIs, and treat embedded JavaScript or embedded files as strong risk signals.",
        generation_config={"response_mime_type": "application/json"},
    )

    prompt = f"""PDF ANALYSIS

Extracted visible text:
{extracted_text[:4000]}

Link annotations found in the PDF (actual click targets, may differ from visible text):
{json.dumps(link_annotations, indent=None)}

URL analysis (typosquat/shortener checks on all found URLs):
{json.dumps(url_analysis, indent=None)}

Structural risk flags (embedded JS, embedded files, encryption):
{json.dumps(risk_flags, indent=None)}

Analyze the attached page image directly for visual phishing indicators
(fake letterhead, spoofed branding, fake signature/payment request UI)
combined with the evidence above. Respond with the same JSON verdict shape as usual."""

    try:
        response = model.generate_content([
            {"mime_type": "image/png", "data": page_image_bytes},
            prompt,
        ])
        raw_text = response.text
    except Exception as e:
        return {
            "verdict": "unknown",
            "confidence": 0,
            "techniques_detected": [],
            "reasoning": [f"PDF analysis failed: {e}"],
        }

    return _clamp_confidence(_parse_json_response(raw_text))